### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by vascofg** [aabed/kubernetes-configmap-rollouts#3]
On my cluster (`v1.8.7`) the container refuses to start, throwing a ```/bin/sh: 1: /updater.sh: Permission denied``` error.

**Comment by aabed** [comment]
@vascofg I have already updated dockerhub 
https://github.com/aabed/kubernetes-configmap-rollouts/issues/3

**Comment by vovkats** [comment]
@aabed I have the same issue

**Comment by aabed** [comment]
@vovkats There's already an opened issue witg that and will fix it soon by updating the docker image

**Comment by aabed** [comment]
@vovkats please refer to https://github.com/aabed/kubernetes-configmap-rollouts/issues/9
